apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::739812930869:user/Eunice_dev
      username: Eunice_dev
      groups:
        - system:main
