apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-training-api-deployment
  labels:
    app: kubernetes-training-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-training-api
  template:
    metadata:
      labels:
        app: kubernetes-training-api
    spec:
      containers:
      - name: kuberentes-training-api
        image: 739812930869.dkr.ecr.us-east-2.amazonaws.com/kuberentes-training
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
